### PR TITLE
Update RCO Flag List

### PR DESCRIPTION
**Pull request by Kaiddd**
I know WINE currently doesn't run Roblox, however this flag list is extremely outdated x

### CODE REVIEW

**Comment by apprehensions** [comment]
No, because RCO needs to be tested, and as roblox no longer works, we cannot test anymore.

I have been meaning to polish the internal usage of RCO by retrieving the version at runtime and disabling it via a build tag.

**Comment by Thelolguy1** [comment]
shelving until we can test

**Comment by Kaiddd** [comment]
> shelving this until we can test it

I highly recommend against implementing RCO, I used to develop it, the owner likes kids

**Comment by EasternBloxxer** [comment]
Do not use RCO.

**Comment by Kaiddd** [comment]
> Do not use RCO.

^
https://cdn.discordapp.com/attachments/1114715172012044358/1115043650318118992/l8x.mp4

**Pull request closed without merging**
