### PR TITLE
util/proc.go: add *bsd support

### PR DESCRIPTION
**Pull request by TeknosQuet**
As of current, `proc.go` only works for Linux due to the differences in the proc filesystem between Linux and other *nix OSes. This pull request adds support for FreeBSD, NetBSD, and any other *nix OS that utilizes `/proc/PID/cmdline`.

### CODE REVIEW

**Comment by TeknosQuet** [comment]
This is already noted in the code, but procfs needs to be enabled for this to work. Technically procfs(5) is deprecated in FreeBSD as of 13.2-RELEASE, but multiple packages such as OpenJDK still use it, and not including a fix in this PR would probably make it impossible for Vinegar to function properly.

**Comment by apprehensions** [comment]
Just remove the build constraint..

**Comment by TeknosQuet** [comment]
Is there an issue?

**Review by apprehensions — CHANGES_REQUESTED** [review]
Rename the file to `proc_linux.go` as is and keep the build constraint. Make another file called `proc_bsd.go` with the BSD implementation and the build constraints.

**Pull request closed without merging**
